[project]
name = "cortex404"
version = "0.1.0"
description = ""
authors = [
    {name = "Yuito"}
]
license = {text = "GNU GPL 3"}
readme = "README.md"
requires-python = ">=3.10,<4.0.0"
dependencies = [
    "aiofiles (>=25.1.0,<26.0.0)",
    "apscheduler (>=3.11.1,<4.0.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "fastapi>=0.122.1",
    "numpy>=2.2.6",
    "opencv-python-headless>=5.0.0.93",
    "pymupdf>=1.28.2",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "python-multipart>=0.0.20",
    "pyzbar>=0.1.9",
    "qrcode[pil]>=8.2",
    "reportlab>=5.0.1",
    "supabase>=2.31.0",
    "tortoise-orm (>=0.25.1,<0.26.0)",
    "uvicorn[standard]>=0.38.0,<0.39.0",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
